# starship.toml




# format = '$all$directory$character'
# A minimal left prompt
format = """$directory$character"""
# palette = "catppuccin_mocha"
add_newline = false

# move the rest of the prompt to the right
right_format = """$git_branch$git_state$python$time"""

[directory]
truncation_length = 1
truncation_symbol = ''

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[git_branch]

[git_state]

[time]
disabled = false

[python]
detect_files = []
detect_folders = []
detect_extensions = []
