# starship.toml


# Run this command to identify performance bottlenecks:
# env STARSHIP_LOG=trace starship timings
# TODO: Look into performance issues:
# Here are the timings of modules in your prompt (>=1ms or output):
# git_status  -  503ms  -   ""
# directory   -    7ms  -   "~ "
# character   -   <1ms  -   "â¯ "
# git_branch  -   <1ms  -   "on î‚  main "
# time        -   <1ms  -   "at 01:25:51 "

# A minimal left prompt
format = """$directory$character"""
# palette = "catppuccin_mocha"
add_newline = false

# move the rest of the prompt to the right
right_format = """$git_branch$git_status$git_state$python$time"""

[directory]
truncation_length = 1
truncation_symbol = ''

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[git_branch]

[git_status]
disabled = true # NOTE: Disabled b/c of performance issues

[git_state]
disabled = false
format = '[\($state( $progress_current of $progress_total)\)]($style) '
# Rebase operations
rebase = '[ğŸ“ REBASING](bold yellow)'
# Merge operations
merge = '[ğŸ”€ MERGING](bold blue)'
# Revert operations
revert = '[âª REVERTING](bold purple)'
# Cherry-pick operations
cherry_pick = '[ğŸ’ PICKING](bold red)'
# Bisect operations (binary search for bugs)
bisect = '[ğŸ” BISECTING](bold cyan)'
# AM (applying mailbox patches)
am = '[ğŸ“¬ APPLYING](bold green)'
# AM with rebase
am_or_rebase = '[ğŸ“¬ AM/REBASE](bold green)'

[time]
disabled = false

[python]
detect_files = []
detect_folders = []
detect_extensions = []
